import Foundation

// Users, roles and privileges (`dbcore::access`). SQL is generated by the core; see `Access`.

/// A role (Postgres) or account (MySQL, with a host).
public struct RoleRef: Hashable, Sendable, Comparable {
    public var name: String
    public var host: String?

    public init(name: String, host: String? = nil) {
        self.name = name
        self.host = host
    }

    /// `name` or `name@host`.
    public var title: String { host.map { "\(name)@\($0)" } ?? name }

    public static func < (a: RoleRef, b: RoleRef) -> Bool {
        (a.name, a.host ?? "") < (b.name, b.host ?? "")
    }
}

public struct Role: Identifiable, Hashable, Sendable {
    public var name: String
    public var host: String?
    /// Postgres `LOGIN`; MySQL: the account isn't locked. Roles that can't log in are groups.
    public var canLogin: Bool
    public var isSuperuser: Bool
    public var canCreateDB: Bool
    public var canCreateRole: Bool
    /// Built in (`pg_*`, `mysql.sys`…).
    public var isSystem: Bool
    /// `nil` = unlimited.
    public var connectionLimit: Int?
    /// Postgres password expiry, as the server prints it.
    public var validUntil: String?
    public var memberOf: [RoleRef]
    public var comment: String?

    public init(
        name: String, host: String? = nil, canLogin: Bool = true, isSuperuser: Bool = false, canCreateDB: Bool = false,
        canCreateRole: Bool = false, isSystem: Bool = false, connectionLimit: Int? = nil, validUntil: String? = nil,
        memberOf: [RoleRef] = [], comment: String? = nil
    ) {
        self.name = name
        self.host = host
        self.canLogin = canLogin
        self.isSuperuser = isSuperuser
        self.canCreateDB = canCreateDB
        self.canCreateRole = canCreateRole
        self.isSystem = isSystem
        self.connectionLimit = connectionLimit
        self.validUntil = validUntil
        self.memberOf = memberOf
        self.comment = comment
    }

    public var reference: RoleRef { RoleRef(name: name, host: host) }
    public var id: RoleRef { reference }
}

/// What a role should be, for creating or editing it.
public struct RoleSpec: Hashable, Sendable {
    public var name = ""
    public var host: String?
    /// New password; empty leaves it unset / unchanged.
    public var password = ""
    public var canLogin = true
    public var isSuperuser = false
    public var canCreateDB = false
    public var canCreateRole = false
    public var connectionLimit: Int?
    public var validUntil: String?
    public var memberOf: [RoleRef] = []

    public init() {}

    /// The role as it is (no password).
    public init(_ role: Role) {
        name = role.name
        host = role.host
        canLogin = role.canLogin
        isSuperuser = role.isSuperuser
        canCreateDB = role.canCreateDB
        canCreateRole = role.canCreateRole
        connectionLimit = role.connectionLimit
        validUntil = role.validUntil
        memberOf = role.memberOf
    }
}

public enum GrantObjectKind: Hashable, Sendable, CaseIterable {
    case server, database, schema, table, sequence, allTables, allSequences

    public var title: String {
        switch self {
        case .server: "Server"
        case .database: "Database"
        case .schema: "Schema"
        case .table: "Table"
        case .sequence: "Sequence"
        case .allTables: "All Tables in Schema"
        case .allSequences: "All Sequences in Schema"
        }
    }
}

/// What a privilege is on. For MySQL, a table's `schema` is its database.
public enum GrantObject: Hashable, Sendable {
    case server
    case database(String)
    case schema(String)
    case table(schema: String, name: String)
    case sequence(schema: String, name: String)
    case allTables(schema: String)
    case allSequences(schema: String)

    public var kind: GrantObjectKind {
        switch self {
        case .server: .server
        case .database: .database
        case .schema: .schema
        case .table: .table
        case .sequence: .sequence
        case .allTables: .allTables
        case .allSequences: .allSequences
        }
    }

    /// "public.orders", "Database app", "All tables in billing"…
    public var title: String {
        switch self {
        case .server: "Server (*.*)"
        case .database(let name): name
        case .schema(let name): name
        case .table(let schema, let name), .sequence(let schema, let name): "\(schema).\(name)"
        case .allTables(let schema): "All tables in \(schema)"
        case .allSequences(let schema): "All sequences in \(schema)"
        }
    }

    public var systemImage: String {
        switch self {
        case .server: "server.rack"
        case .database: "cylinder"
        case .schema: "folder"
        case .table, .allTables: "tablecells"
        case .sequence, .allSequences: "number"
        }
    }
}

public struct PrivilegeSet: Hashable, Sendable {
    public var privileges: [String]
    /// Held `WITH GRANT OPTION`.
    public var grantable: Bool

    public init(privileges: [String] = [], grantable: Bool = false) {
        self.privileges = privileges
        self.grantable = grantable
    }

    public var isEmpty: Bool { privileges.isEmpty }
}

/// The privileges a role holds on one object.
public struct ObjectPrivileges: Identifiable, Hashable, Sendable {
    public var object: GrantObject
    public var privileges: PrivilegeSet
    public var id: GrantObject { object }

    public init(object: GrantObject, privileges: PrivilegeSet) {
        self.object = object
        self.privileges = privileges
    }
}

public enum AccessChange: Hashable, Sendable {
    case createRole(RoleSpec)
    case alterRole(Role, RoleSpec)
    case dropRole(RoleRef)
    case setPrivileges(role: RoleRef, object: GrantObject, before: PrivilegeSet, after: PrivilegeSet)
    /// Replaces `role`'s privileges in `context.database` with `level`.
    case setDatabaseLevel(role: RoleRef, context: DatabaseLevelContext, level: DatabaseLevel)
}

/// A role's privileges on one database of the server.
public struct DatabaseAccess: Identifiable, Hashable, Sendable {
    public var database: String
    /// Granted on the database itself (Postgres `CONNECT`…, MySQL `db.*`).
    public var privileges: PrivilegeSet
    /// Postgres: PUBLIC may connect, so any role can.
    public var everyoneCanConnect: Bool
    /// Owners have every privilege on their database.
    public var isOwner: Bool
    /// From the database-level privileges only: exact for MySQL; Postgres roles with privileges there
    /// show `.custom` until `databaseLevel(of:in:)` reads the database.
    public var level: DatabaseLevel
    public var id: String { database }

    public init(database: String, privileges: PrivilegeSet, everyoneCanConnect: Bool = false, isOwner: Bool = false, level: DatabaseLevel = .noAccess) {
        self.database = database
        self.privileges = privileges
        self.everyoneCanConnect = everyoneCanConnect
        self.isOwner = isOwner
        self.level = level
    }
}

/// How much a role may do in one database (see `Access.levels`). Titles come from the core.
public enum DatabaseLevel: Hashable, Sendable {
    case noAccess, connect, readOnly, readWrite, schemaChanges, custom
}

/// A role's level in one database, and what's needed to change it (read in that database).
public struct DatabaseLevelContext: Hashable, Sendable {
    public var database: String
    public var level: DatabaseLevel
    public var privileges: PrivilegeSet
    /// Postgres: the schemas a level applies to.
    public var schemas: [String]
    /// Postgres: roles whose future objects get default privileges.
    public var owners: [String]

    public init(database: String, level: DatabaseLevel, privileges: PrivilegeSet, schemas: [String] = [], owners: [String] = []) {
        self.database = database
        self.level = level
        self.privileges = privileges
        self.schemas = schemas
        self.owners = owners
    }
}

public struct AccessStatement: Hashable, Sendable {
    public var sql: String
    /// `sql` with passwords masked.
    public var display: String
}

/// What a database lets you manage, so the UI only offers what works.
public struct AccessFeatures: Hashable, Sendable {
    public var hosts: Bool
    public var superuser: Bool
    public var createDB: Bool
    public var createRole: Bool
    public var validUntil: Bool
    public var connectionLimit: Bool
    public var membership: Bool
    /// Privileges are per database (Postgres): grants shown are the current database's.
    public var grantsPerDatabase: Bool
    public var objectKinds: [GrantObjectKind]
}

/// Static helpers backed by the core (implemented in `RustDriver.swift`).
public enum Access {}
