# Windows (MSVC): link the C runtime statically, so dbear.exe doesn't need the Visual C++
# Redistributable (vcruntime140.dll) on the machine. A `cfg(...)` key, not the target triple:
# cargo-xwin sets CARGO_TARGET_<triple>_RUSTFLAGS, which would replace a triple key.
[target.'cfg(all(windows, target_env = "msvc"))']
rustflags = ["-C", "target-feature=+crt-static"]
